#!/usr/bin/env bash
# Build a single-binary `piicatcher` sidecar via PyInstaller and drop it into
# src-tauri/binaries/piicatcher-<target-triple>, which is where Tauri's
# `externalBin` config (tauri.conf.json) looks.
#
# Tauri requires the binary filename to have the host target triple suffix,
# e.g. `piicatcher-aarch64-apple-darwin`. We resolve that via `rustc -vV`.
#
# Prereqs:
#   - A working Python 3.10 with piicatcher installed (`pip install piicatcher`).
#     On Apple Silicon + recent Xcode the dbcat-pinned greenlet 2.x will fail
#     to build — see desktop/README.md for the known issue and workarounds.
#   - PyInstaller (`pip install pyinstaller`).
#
# Usage:
#   bash desktop/scripts/build-piicatcher-sidecar.sh
#
# Optional env:
#   PYTHON     — path to the python interpreter with piicatcher installed
#                (default: `python`)
#   TARGET     — override the target triple (default: detected via rustc)

set -euo pipefail

PYTHON="${PYTHON:-python}"

# Detect host target triple via rustc — matches what Tauri expects.
TARGET="${TARGET:-$(rustc -vV | awk '/^host:/ {print $2}')}"
if [[ -z "$TARGET" ]]; then
  echo "error: could not determine target triple. Set TARGET=... explicitly." >&2
  exit 1
fi

echo "==> Target: $TARGET"
echo "==> Python: $PYTHON"

# Confirm piicatcher is importable from the chosen Python.
if ! "$PYTHON" -c "import piicatcher" 2>/dev/null; then
  echo "error: \`$PYTHON -c 'import piicatcher'\` failed." >&2
  echo "       install piicatcher into the chosen interpreter first." >&2
  exit 1
fi

# Confirm PyInstaller is present.
if ! "$PYTHON" -c "import PyInstaller" 2>/dev/null; then
  echo "==> Installing PyInstaller into the active Python..."
  "$PYTHON" -m pip install --quiet pyinstaller
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SIDECAR_DIR="$SCRIPT_DIR/../src-tauri/binaries"
BUILD_DIR="$SCRIPT_DIR/../.pyinstaller-build"
mkdir -p "$SIDECAR_DIR" "$BUILD_DIR"

# Write a tiny entry-point that delegates to piicatcher's typer app.
ENTRY="$BUILD_DIR/piicatcher_entry.py"
cat > "$ENTRY" <<'PY'
# Auto-generated by build-piicatcher-sidecar.sh. Do not edit by hand.
from piicatcher.command_line import app
if __name__ == "__main__":
    app()
PY

echo "==> Running PyInstaller (this can take a minute)..."
"$PYTHON" -m PyInstaller \
  --onefile \
  --name "piicatcher-$TARGET" \
  --distpath "$SIDECAR_DIR" \
  --workpath "$BUILD_DIR/work" \
  --specpath "$BUILD_DIR" \
  --noconfirm \
  --clean \
  --collect-submodules dbcat \
  --collect-submodules piicatcher \
  --collect-data dbcat \
  --hidden-import goog_stats \
  "$ENTRY"

# Smoke test.
BIN="$SIDECAR_DIR/piicatcher-$TARGET"
if [[ -x "$BIN" ]]; then
  echo "==> Built: $BIN"
  "$BIN" --version || {
    echo "warning: built binary fails to run --version. Bundling is likely incomplete." >&2
  }
else
  echo "error: expected binary at $BIN but it was not produced." >&2
  exit 1
fi

echo "==> Done. The Tauri build will pick this up via tauri.conf.json externalBin."
